### ISSUE TITLE
system.adapter.squeezeboxrpc.0 terminated with code 1 (JS_CONTROLLER_STOPPED) with iobroker js-controller 6.0.9

### ISSUE THREAD

**Issue by matty67** [oweitman/ioBroker.squeezeboxrpc#75]
After updating js-controller from 5.0.19 to 6.0.9 the adapter stops with the following error.

2024-08-01 16:32:47.641  - [32minfo[39m: host.iobroker2 instance system.adapter.squeezeboxrpc.0 in version "1.3.9" started with pid 1386
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]: /opt/iobroker/node_modules/iobroker.squeezeboxrpc/squeezeboxrpc.js:30
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     return adapter = utils.adapter(Object.assign({}, options, {
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:                            ^
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]: TypeError: utils.adapter is not a function
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at startAdapter (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/squeezeboxrpc.js:30:28)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.squeezeboxrpc/squeezeboxrpc.js:71:5)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1364:14)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1203:32)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:1019:12)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]:     at node:internal/main/run_main_module:28:49
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 Caught by controller[0]: Node.js v18.20.2
2024-08-01 16:32:48.184  - [31merror[39m: host.iobroker2 instance system.adapter.squeezeboxrpc.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Comment by oweitman** [comment]
Thank you, I look into it

**Comment by oweitman** [comment]
I tried to recreate this issue with a clean isntall of iobroker 6.0.9 and admin 7.0.22 in a docker container.
The adapter could be installed and the error messages mentioned did not appear.
Can you please uninstall the adapter and reinstall it?

**Comment by matty67** [comment]
Yes. That works. Thx a lot.
